pipeline{
        agent any
        stages{
            stage('Bin bashing'){
                steps{
                    sh "#!/bin/bash"
                }
            }
            stage('Exporting global variables'){
                steps{
                    sh "export DATABASE_URI"
                }
            }
            stage('Installing apt dependencies'){
                steps{
                    sh "sudo apt update"
                    sh "sudo apt install python3-venv python3-pip python3 -y"
                    sh 'echo "Its working"'
                }
            }
            stage('Creating virtual env'){
                steps{
                    sh "python3 -m venv venv"
                }
            }
            stage('Activating virtual env'){
                steps{
                    sh "source/bin/activate"
                }
            }
            stage('Installing requirements'){
                steps{
                    sh 'pip3 install -r requirements.txt'
                }
            }
            stage('Running tests'){
                steps{
                    sh "python3 -m pytest --cov=tests --cov-report term missing"
                }
            }
            stage("Creating DB schema"){
                steps{
                    sh "python3 create.py"
                }
            }
        }
}