pipeline{
        agent any
        environment {
            DATABASE_URI = credentials("DB_URI")
            RUN_APP = "false"
        }
        stages{
            stage('Setup'){
                steps{
                    sh "bash application/jenkins/setup.sh"
                }
            }
            stage('Test'){
                steps{
                    sh "bash application/jenkins/test.sh"
                }
            } 
            stage('Create Schema'){
                steps{
                    sh "bash application/jenkins/create_schema.sh"
                }
            }
            stage('Run'){
                steps{
                   script{
                       if(env.RUN_APP = "true") {
                           sh "bash application/jenkins/run_app.sh"
                       }
                   }
                }
            }
        }
}